
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AnthonyCee
 */
public class companyname extends javax.swing.JInternalFrame {
 Connection con =Server.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form companyname
     */
    public companyname() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btnsub = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btncng = new javax.swing.JButton();
        oldname = new javax.swing.JLabel();
        txtoldname = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("CONPANY NAME EDITOR");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/usedimages/icons8_Name_Tag_16.png"))); // NOI18N

        jLabel1.setText("Company Name");

        btnsub.setText("Submit");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btncng.setText("Change");
        btncng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncngActionPerformed(evt);
            }
        });

        oldname.setText("Company OldName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsub)
                .addGap(28, 28, 28)
                .addComponent(btncng)
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(oldname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtoldname)
                    .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtoldname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void companyname(){
 index DASH = new index();
     try {
         String sqls = "select * from companyname ";
         ps = con.prepareStatement(sqls);
         rs =ps.executeQuery();
         while(rs.next()){
         String add = rs.getString("Company_Name");
         DASH.iname.setText(add);
         }
     } catch (SQLException ex) {
         Logger.getLogger( index.class.getName()).log(Level.SEVERE, null, ex);
     }
}
    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed

        int conf =    JOptionPane.showConfirmDialog(this, "Are you sure you want to create this company name as" +"" + ""  .concat(txtname.getText()),"CONFIRMATION",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(txtname.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Please Enter the company Name");
     
     }else{
        if(conf == JOptionPane.YES_OPTION){
        try {
            String sql3 = "select * from companyname";
            ps = con.prepareStatement(sql3);
            rs = ps.executeQuery();
            if(!rs.next()){
            try {
                // TODO add your handling code here:
                
                String sql = "Insert into  `companyname`(Company_Name) Values(?)";
                ps = con.prepareStatement(sql);
                ps.setString(1, txtname.getText());
                int ok = ps.executeUpdate();
                if (ok>0){
                    JOptionPane.showMessageDialog(this, "Company name created successfully");
                     companyname();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Company name was not created, please try again");
                Logger.getLogger(companyname.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            }else{
                             int conf2 = JOptionPane.showConfirmDialog(this, "You have an already existing Company Name, Do want to change the name?","Comfirmation",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

             if(conf2 == JOptionPane.YES_OPTION){
            companyname cn = new companyname();
                           JDesktopPane desktopPane = getDesktopPane();
                           desktopPane.add(cn);
                          cn.show();
                          this.hide();
                          btnsub.hide();
                          
             }
             else{}
             
            }
        } catch (SQLException ex) {
                Logger.getLogger(companyname.class.getName()).log(Level.SEVERE, null,ex);
     }
        
        
        }else{}
        
        
        }  
    }//GEN-LAST:event_btnsubActionPerformed

    private void btncngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncngActionPerformed
        // TODO add your handling code here:
       
         int conf =    JOptionPane.showConfirmDialog(this, "Are you sure you want to Change this company name as" +"" + ""  .concat(txtname.getText()),"CONFIRMATION",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(txtname.getText().equals("") || txtoldname.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Empty field detected, Please Enter the missing field");
     
     }else{
        if(conf == JOptionPane.YES_OPTION){
        try {
         // TODO add your handling code here:
         String sql = "update   `companyname` set Company_Name =? where Company_Name = ?";
         ps = con.prepareStatement(sql);
         ps.setString(1, txtname.getText());
           ps.setString(2, txtoldname.getText());
         int ok = ps.executeUpdate();
         if (ok>0){
         JOptionPane.showMessageDialog(this, "Company name was updated successfully");
            companyname();
         
         }
     } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this, "Company name was not created, please try again");
         Logger.getLogger(companyname.class.getName()).log(Level.SEVERE, null, ex);
     }
        }else{}
        
        }  
    }//GEN-LAST:event_btncngActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btncng;
    public static javax.swing.JButton btnsub;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel oldname;
    private javax.swing.JTextField txtname;
    public static javax.swing.JTextField txtoldname;
    // End of variables declaration//GEN-END:variables
}
