/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author AnthonyCee
 */
public class mgtexpbooK extends javax.swing.JInternalFrame {
Connection con =Server.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form mgtexpbooK
     */
    public mgtexpbooK() {
        initComponents();
        txtdatee.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtpurpp = new javax.swing.JTextField();
        txtdatee = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiscripp = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtamtt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnamee = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtsigg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Purpose");

        txtdiscripp.setColumns(20);
        txtdiscripp.setRows(5);
        jScrollPane1.setViewportView(txtdiscripp);

        jLabel2.setText("Discription");

        jLabel3.setText("Name");

        jLabel4.setText("Amount");

        jLabel5.setText("Date");

        txtnamee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameeActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Admin Signature");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpurpp)
                            .addComponent(txtnamee)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtamtt)
                            .addComponent(txtdatee, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsigg, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpurpp, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamee, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtamtt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtdatee, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtsigg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameeActionPerformed
public void showme(){
        try {
            String date = ((JTextField)txtdatee.getDateEditor().getUiComponent()).getText();
            String s = "SELECT * FROM `dailyanalysistable` WHERE Date = '"+date+"'";
            ps = con.prepareStatement(s);
            rs = ps.executeQuery();
            if(rs.next()){
               
         
               
               vendor. ldexp.setText(rs.getString("TotalExpenses"));
               
               
                
            }       } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //submit statement
        try{
            if( txtdiscripp.getText().equals("")||txtpurpp.getText().equals("")||txtnamee.getText().equals("")||txtamtt.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Empty field detected, fillin the field to proceed");
            }else{
                try{
                    String date2 = ((JTextField)Expensesbook.txtdate.getDateEditor().getUiComponent()).getText();
                    int conf = JOptionPane.showConfirmDialog(this,"Do you want to submit this Record?","Confirmation", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

                    String exp = "INSERT INTO `dailyexpensestable`( `Expenses_Description`, `Purpose`, `Name_Of_Signatory`, `Amount`,`MgtSignature`, `Date`) VALUES (?,?,?,?,?,?)";
                    ps = con.prepareStatement(exp);
                    ps.setString(1, txtdiscripp.getText());
                    ps.setString(2, txtpurpp.getText());
                    ps.setString(3, txtnamee.getText());
                    ps.setString(4, txtamtt.getText());
                     ps.setString(5, txtsigg.getText());
                    ps.setString(6, date2);

                    int ok = ps.executeUpdate();
                    if(conf == JOptionPane.YES_OPTION){
                        if(ok>0){

                            JOptionPane.showMessageDialog(this,"Submission was Successful");

                        }else{  JOptionPane.showMessageDialog(this,"Submission failed");}

                    }
                }catch(Exception ex){}

                //this will give feedback to the dailyanlysis table for accountability

                try {
                    String date = ((JTextField)Expensesbook.txtdate.getDateEditor().getUiComponent()).getText();
                    String qry = "select * from  `dailyanalysistable` where Date = '"+date+"'";
                    ps = con.prepareStatement(qry);
                    rs = ps.executeQuery();

                    if(!rs.next()){

                        try {

                            // Submiting the b/f,opening balance and the date

                            String sql5 = "INSERT INTO `dailyanalysistable`( `TotalDailySales`, `TotalExpenses`, `NetBalance`, `Date`) VALUES (?,?,?,?)";
                            ps = con.prepareStatement(sql5);
                            ps.setDouble(1, 0);
                            ps.setString(2, txtamtt.getText());

                            ps.setDouble (3,0);
                            ps.setString (4,date);

                            int k1 = ps.executeUpdate();
                            if(k1>0){

                                JOptionPane.showMessageDialog(this,"Submission was Successfullllllll");
                                showme();
                            }

                        } catch (SQLException ex) {

                            JOptionPane.showMessageDialog(this,"Submission Failed");
                            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }else{
                        try{

                            String sql12 = "UPDATE `dailyanalysistable` SET `TotalExpenses`= (`TotalExpenses` + '"+txtamtt.getText()+"') where Date = '"+date+"'";
                            ps = con.prepareStatement(sql12);
                            int q = ps.executeUpdate();

                            if(q>0){

                                JOptionPane.showMessageDialog(this,"Submission was Successful");
                                showme();
                            }
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this,"Update failed");
                            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                } catch (SQLException ex) {
                    Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);

                }
            }

        }catch(Exception ex){}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtamtt;
    public static com.toedter.calendar.JDateChooser txtdatee;
    private javax.swing.JTextArea txtdiscripp;
    private javax.swing.JTextField txtnamee;
    private javax.swing.JTextField txtpurpp;
    private javax.swing.JTextField txtsigg;
    // End of variables declaration//GEN-END:variables
}
