
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AnthonyCee
 */
public class slide extends javax.swing.JFrame {
JLabel pic;
Timer tm;
int x = 0;
String[] list ={

"C:\\Users\\AnthonyCee\\Documents\\NetBeansProjects\\QUICKSTOCKER\\src\\usedimages\\brain3.png",
    "C:\\Users\\AnthonyCee\\Documents\\NetBeansProjects\\QUICKSTOCKER\\src\\usedimages\\res.png",
    "C:\\Users\\AnthonyCee\\Documents\\NetBeansProjects\\QUICKSTOCKER\\src\\usedimages\\mn.png",
    "C:\\Users\\AnthonyCee\\Documents\\NetBeansProjects\\QUICKSTOCKER\\src\\usedimages\\bmf.png",
    "C:\\Users\\AnthonyCee\\Documents\\NetBeansProjects\\QUICKSTOCKER\\src\\usedimages\\quk.png"
       
      
};
    /**
     * Creates new form slide
     */
    public slide() {
       //initComponents();
       super ("Java SlideShow");
       pic = new JLabel();
       pic.setBounds(10, 8, 100, 50);
      setImageSize(4);
      
      tm = new Timer(100,new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e) {
          setImageSize(x);
          x +=1;
          if(x>= list.length)
          
          x= 0;
                  
          
           
           
           }
       });
     tm.start();
    } 
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

public void setImageSize(int i){
  ImageIcon icon = new ImageIcon(list[i]);
  Image img = icon.getImage();
  Image newimg = img.getScaledInstance(pic.getWidth(),pic.getHeight(),Image.SCALE_SMOOTH);
  ImageIcon newImc = new ImageIcon(newimg);
  
  }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new slide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
