
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AnthonyCee
 */
public class STOCKER extends javax.swing.JInternalFrame {
Connection con =Server.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form STOCKER
     */
    public STOCKER() {
        initComponents();
        selection();
        dater.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdis = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtbkp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtupr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtgp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnupd = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        citem = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        dater = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmes = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("STOCKER FORM");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/usedimages/addsb.png"))); // NOI18N

        jLabel1.setText("Item Name");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Discription");

        jLabel3.setText(" Quantity");

        txtbkp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbkpKeyReleased(evt);
            }
        });

        jLabel4.setText("Bulk Price");

        txtsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtspKeyReleased(evt);
            }
        });

        jLabel5.setText("Saling Price");

        txtupr.setEnabled(false);

        jLabel6.setText("Unit Price");

        txtgp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Grand Profit");

        jLabel9.setText("Item To Be Update");

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnupd.setText("Update");
        btnupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdActionPerformed(evt);
            }
        });

        btnsub.setText("Submit");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });

        jButton5.setText("Search");

        citem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        citem.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                citemPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Date");

        jLabel11.setText("Measurement");

        txtmes.setToolTipText("e.g kg,,pcs,gallons etc");
        txtmes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmesKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtname)
                                            .addComponent(txtdis)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtupr, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtqty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtmes)))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtbkp, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                            .addComponent(txtgp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtsp)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(citem, 0, 178, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(txtsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnupd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(134, 134, 134))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(dater, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdis, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtqty, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtbkp, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtupr, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtsp, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtgp, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dater, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(citem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnupd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed
  public void selection(){
    //pupulating the combo box with Items
        try {
            String select = "SELECT * FROM `admintable`  ";
            ps = con.prepareStatement(select);
            rs = ps.executeQuery();
            while(rs.next()){
            citem.addItem(rs.getString("Itemname"));
            
            
            
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }



}
    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
        String date = ((JTextField)dater.getDateEditor().getUiComponent()).getText();
        int conf =JOptionPane.showConfirmDialog(this,"Do you want to add this item","Warning",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
if(txtname.getText().equals("")||txtdis.getText().equals("")|| txtqty.getText().equals("")||txtbkp.getText().equals("")||txtsp.getText().equals("")||txtgp.getText().equals("") ||txtmes.getText().equals("") ){
  JOptionPane.showMessageDialog(this,"Empty field detected, fillin the field to proceed");

}else{  
    if(conf == JOptionPane.YES_OPTION){
         
         try{
              //checking if username already exist or not
                String user = "select COUNT(*) AS total from `admintable` where ItemName = ? ";
                ps = con.prepareStatement(user);
                ps.setString(1, txtname.getText());
               
                // ps.setString(1, pin.getText());

                rs = ps.executeQuery();
                while(rs.next()){

                    if(rs.getInt("total")>0){
                        JOptionPane.showMessageDialog(this,"This Item already exist in the database");
                    }
                    else{
        try {
            
        // TODO add your handling code here:
        String sql = "INSERT INTO `admintable`( `ItemName`, `Description`, `Quantity`, `BulkPrice`, `Measurement`, `UnitPrice`, `SalesPrice`, `GrandProfit`,Date) VALUES (?,?,?,?,?,?,?,?,?)";
       ps = con.prepareStatement(sql);
        ps.setString(1, txtname.getText());
         ps.setString(2, txtdis.getText());
          ps.setString(3, txtqty.getText());
           ps.setString(4, txtbkp.getText());
          
              ps.setString(5,   txtmes.getText());
              ps.setString(6, txtupr.getText());
             ps.setString(7, txtsp.getText());
         ps.setString(8, txtgp.getText()); 
         ps.setString(9, date); 
         
         int ok = ps.executeUpdate();
       
         if(ok>0){
       // JOptionPane.showMessageDialog(this,"Stock was added successfully");
         
         }
        
    } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,"Stock was not submitted successfully");
        Logger.getLogger(STOCKER.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
        
         try {
            
        // TODO add your handling code here:
        String sql1 = "INSERT INTO  `detailtable`( `ItemName`, `Description`, `QuantityPurchased`, `BulkPrice`, `UnityPrice`, `QuantityOut`, `BalanceQuantity`, `Date`) VALUES (?,?,?,?,?,?,?,?)";
       ps = con.prepareStatement(sql1);
        ps.setString(1, txtname.getText());
         ps.setString(2, txtdis.getText());
          ps.setString(3, txtqty.getText());
           ps.setString(4, txtbkp.getText());
           
            ps.setString(5, txtupr.getText());
             ps.setDouble(6, 0);
              ps.setDouble(7, 0);
         ps.setString(8, date); 
         
         int ok = ps.executeUpdate();
         if(ok>0){
         JOptionPane.showMessageDialog(this,"Stock was submitted successfully");
          fetchdata();
          selection();
         }
        
    } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,"Stock was not submitted successfully");
        Logger.getLogger(STOCKER.class.getName()).log(Level.SEVERE, null, ex);
    }
                    }
                }
         }catch(Exception ex){}   
   }else{}
           
           }       
         
    }//GEN-LAST:event_btnsubActionPerformed

    private void txtbkpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbkpKeyReleased
        // calculating the 1unit price
        double qty = Double.parseDouble(txtqty.getText());
        double bkp = Double.parseDouble(txtbkp.getText());
        double result = bkp/qty;
        DecimalFormat df = new DecimalFormat("#.00");
        String ans = df.format(result);
        txtupr.setText("N" + ans);
    }//GEN-LAST:event_txtbkpKeyReleased

    private void txtspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtspKeyReleased
        // calculating the grand profit
         // calculating the 1unit price
        double qty = Double.parseDouble(txtqty.getText());
        double sp = Double.parseDouble(txtsp.getText());
         double bkp = Double.parseDouble(txtbkp.getText());
        double result = sp * qty;
        double profit = result - bkp;
         DecimalFormat df = new DecimalFormat("#.00");
        String ans = df.format(profit);
       
     txtgp.setText("N"+ ans);
    }//GEN-LAST:event_txtspKeyReleased

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
         try {
            // search and display the items on both combo box and table
            String search = "SELECT * FROM `admintable` WHERE ItemName like '" + txtsearch.getText() + "%'";
            ps = con.prepareStatement(search);
            rs = ps.executeQuery();
             citem.removeAllItems();
             
            while(rs.next()){
          
            citem.addItem(rs.getString("ItemName"));
            
            
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
 
    }//GEN-LAST:event_txtsearchKeyReleased

    public void fetchdata(){
    
      //display the insert or updated item immediadly on the table
        try {
              String q = "select * from admintable ";
            ps = con.prepareStatement(q);
             rs = ps.executeQuery();
             
          index.tableshow.setModel(DbUtils.resultSetToTableModel(rs)); 
             
        } catch (SQLException ex) {
            
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
    
     
       
}
    private void btnupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdActionPerformed
     String date = ((JTextField)dater.getDateEditor().getUiComponent()).getText();
        int conf =JOptionPane.showConfirmDialog(this,"Do you want to update this item","Warning",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
      if(txtname.getText().equals("")||txtdis.getText().equals("")|| txtqty.getText().equals("")||txtbkp.getText().equals("")||txtsp.getText().equals("")||txtgp.getText().equals("")||txtmes.getText().equals("")  ){
  JOptionPane.showMessageDialog(this,"Empty field detected, fillin the field to proceed");

}else{  
        try {
        // Updating the admin table for the stock
        String sql = "UPDATE `admintable` SET `ItemName`=?,`Description`=?,`Quantity`=(`Quantity` + ?),`BulkPrice`=?,`Measurement`=?,`UnitPrice`=?,`SalesPrice`=?,`GrandProfit`=?,`Date`= ? WHERE `ItemName` = ?";
        ps = con.prepareStatement(sql);
        ps.setString(1, txtname.getText());
        ps.setString(2, txtdis.getText());
        ps.setString(3, txtqty.getText());
        ps.setString(4, txtbkp.getText());
         
          ps.setString(5, txtmes.getText());
        ps.setString(6, txtupr.getText());
        ps.setString(7, txtsp.getText());
        ps.setString(8, txtgp.getText());
         ps.setString(9, date);
          ps.setString(10, citem.getSelectedItem().toString());
        int ok = ps.executeUpdate();
        if(conf == JOptionPane.YES_OPTION){
        if(ok>0){
           // JOptionPane.showMessageDialog(this,"Stock was updated successfully");
             fetchdata();
             selection();
        }
        }else{}
    } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,"Stock  update not successful");
        Logger.getLogger(STOCKER.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
         try {
        // updating the details table that show the details of the sale
        String sql1 = "UPDATE `detailtable` SET `ItemName`=?,`Description`=?,`QuantityPurchased`= (`BalanceQuantity`+ ?),`BulkPrice`=?,`UnityPrice`=?,`Date`=?  WHERE `ItemName` = ?";
        ps = con.prepareStatement(sql1);
        ps.setString(1, txtname.getText());
        ps.setString(2, txtdis.getText());
        ps.setString(3, txtqty.getText());
        ps.setString(4, txtbkp.getText());
         
        ps.setString(5, txtupr.getText());
        ps.setString(6, date);
        
          ps.setString(7, citem.getSelectedItem().toString());
        int ok = ps.executeUpdate();
        if(conf == JOptionPane.YES_OPTION){
        if(ok>0){
            JOptionPane.showMessageDialog(this,"Stock was updated successfully");
             fetchdata();
             selection();
             
        }
        }else{}
    } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,"Stock  update not successful");
        Logger.getLogger(STOCKER.class.getName()).log(Level.SEVERE, null, ex);
    }
      }
    }//GEN-LAST:event_btnupdActionPerformed

    private void citemPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_citemPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         try {
             String combo = (String)citem.getSelectedItem();
            String search1 = "SELECT * FROM `admintable` WHERE ItemName = ?";
            ps = con.prepareStatement(search1);
            ps.setString(1,combo);
            rs = ps.executeQuery();
            // citem.removeAllItems();
            while(rs.next()){
           
            String add1 = rs.getString("ItemName");
            txtname.setText( add1);
           
           String add2 = rs.getString("Description");
            txtdis.setText( add2);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);}

    }//GEN-LAST:event_citemPopupMenuWillBecomeInvisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            txtdis.setText( "");
             txtname.setText( "");
              txtqty.setText("");
        txtbkp.setText("");
         txtupr.setText("");
         txtsp.setText("");
        txtgp.setText("");
            
            
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtmesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmesKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnsub;
    public static javax.swing.JButton btnupd;
    private javax.swing.JComboBox<String> citem;
    private com.toedter.calendar.JDateChooser dater;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtbkp;
    private javax.swing.JTextField txtdis;
    private javax.swing.JLabel txtgp;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsp;
    private javax.swing.JTextField txtupr;
    // End of variables declaration//GEN-END:variables
}
