

import java.awt.Font;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AnthonyCee
 */
public class vendor extends javax.swing.JFrame {

    Connection con = Server.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    double accum;
    double grdaccuma;
    
  //  String billNO = "";
    Double totalAmount = 0.0;
    Double balance = 0.0;
    Double bHeight = 0.0;
    
    ArrayList<String> itemName = new ArrayList<>();
    ArrayList<String> Quantity = new ArrayList<>();
ArrayList<String> itemPrice = new ArrayList<>();
ArrayList<String> subtotal = new ArrayList<>();
    /**
     * Creates new form NewJFrame
     */
    public vendor() {
        initComponents();
        this.setLocationRelativeTo(null);
        fetchdata();
        idate.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        showme();
        selection();
        addmin();
        companyname();
        Icon();
    }

    
      public void Icon(){
   setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("fastest.png")));
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        iname = new javax.swing.JLabel();
        idate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        dplay = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ltotal = new javax.swing.JLabel();
        lgt = new javax.swing.JLabel();
        lprice = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        citem = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lstock = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableshow = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtqty = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ldsale = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ldexp = new javax.swing.JLabel();
        ldbal = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtcash = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtbal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUICKSTOCKER>VENDOR");
        setPreferredSize(new java.awt.Dimension(1150, 750));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));

        iname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        iname.setForeground(new java.awt.Color(255, 255, 255));
        iname.setText("##");

        idate.setEnabled(false);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedimages/icons8_General_Ledger_48.png"))); // NOI18N
        jLabel9.setToolTipText("Expenses Book");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedimages/Search_48px.png"))); // NOI18N
        jLabel5.setToolTipText("Search Item");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(181, 181, 181)
                .addComponent(iname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(idate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(iname)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addComponent(jLabel5)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setTitle("SALES/VENDOR MART");
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/fastest.png"))); // NOI18N
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DAILY SUMMARY");

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL AMOUNT");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("GRAND TOTAL");

        ltotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ltotal.setForeground(new java.awt.Color(153, 153, 0));
        ltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotal.setText("0.00");
        ltotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lgt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgt.setForeground(new java.awt.Color(102, 0, 51));
        lgt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgt.setText("0.00");
        lgt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lprice.setForeground(new java.awt.Color(0, 51, 51));
        lprice.setToolTipText("Price of the selected item");
        lprice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("SEARCH ITEM");

        txtsearch.setToolTipText("Search for Item here");
        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsearchFocusGained(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("PRICE");

        citem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        citem.setToolTipText("List of Items");
        citem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                citemItemStateChanged(evt);
            }
        });
        citem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                citemAncestorMoved(evt);
            }
        });
        citem.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                citemPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                citemPopupMenuWillBecomeVisible(evt);
            }
        });
        citem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citemActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ITEM");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("QUTY IN STOCK");

        lstock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lstock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableshow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tableshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableshow.setToolTipText("0.00");
        tableshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableshowMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableshow);

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtqty.setToolTipText("enter item quantity demanded by a customer");
        txtqty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtqtyFocusGained(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("QUTY");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("DAILY SUMMARY");

        ldsale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ldsale.setForeground(new java.awt.Color(153, 0, 153));
        ldsale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ldsale.setText("0.00");
        ldsale.setToolTipText("DAILY SALES");
        ldsale.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("DAILY SALE");

        ldexp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ldexp.setForeground(new java.awt.Color(153, 0, 0));
        ldexp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ldexp.setText("0.00");
        ldexp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ldbal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ldbal.setForeground(new java.awt.Color(0, 51, 51));
        ldbal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ldbal.setText("0.00");
        ldbal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("DAILY EXPENSES");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("DAILY BALANCE");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jButton4.setText("REFRESH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Cash");

        txtcash.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        txtcash.setText("N 0.00");
        txtcash.setToolTipText("Enter the Amount issue by a customer");
        txtcash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcashFocusGained(evt);
            }
        });
        txtcash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcashKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Balance");

        txtbal.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        txtbal.setForeground(new java.awt.Color(0, 51, 51));
        txtbal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbal.setText("N 0.00");
        txtbal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setBackground(new java.awt.Color(102, 0, 51));
        jLabel14.setForeground(new java.awt.Color(102, 0, 102));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedimages/WhatsApp_48px.png"))); // NOI18N
        jLabel14.setText("+2347034965611");

        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedimages/Gmail_48px.png"))); // NOI18N
        jLabel17.setText("jeacosoft@gmail.com");

        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedimages/Phone_48px.png"))); // NOI18N
        jLabel18.setText("+2348085189422");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcash, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtbal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator3)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8))
                                                    .addGap(24, 24, 24)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtsearch)
                                                        .addComponent(citem, 0, 174, Short.MAX_VALUE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel15))
                                                        .addComponent(jLabel12))
                                                    .addGap(10, 10, 10)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtqty)
                                                        .addComponent(lprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lgt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel16))
                                            .addComponent(ldsale, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel22))
                                            .addComponent(ldexp, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel23))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(ldbal, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22))
                            .addComponent(jScrollPane2)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel11))
                                    .addComponent(citem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel10))
                                    .addComponent(lprice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(9, 9, 9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lgt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lstock, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel12)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel13))
                            .addComponent(txtbal, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(txtcash))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ldbal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ldsale, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(ldexp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(62, 62, 62)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
        );

        dplay.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dplayLayout = new javax.swing.GroupLayout(dplay);
        dplay.setLayout(dplayLayout);
        dplayLayout.setHorizontalGroup(
            dplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        dplayLayout.setVerticalGroup(
            dplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dplayLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Profile Account");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedimages/icons8_Sign_Out_16.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedimages/icons8_General_Ledger_16.png"))); // NOI18N
        jMenuItem3.setText("Expenses Book");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help?");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dplay)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dplay))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void companyname(){

     try {
         String sqls = "select * from companyname ";
         ps = con.prepareStatement(sqls);
         rs =ps.executeQuery();
         while(rs.next()){
         String add = rs.getString("Company_Name");
         iname.setText(add);
         }
     } catch (SQLException ex) {
         Logger.getLogger( index.class.getName()).log(Level.SEVERE, null, ex);
     }


}
    public void fetchdata() {

        try {
            String q = "select id, ItemName, Description,SalesPrice from admintable ";
            ps = con.prepareStatement(q);
            rs = ps.executeQuery();

            tableshow.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {

            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void selection() {
        //pupulating the combo box with Items
        try {
            String select = "SELECT * FROM `admintable`  ";
            ps = con.prepareStatement(select);
            rs = ps.executeQuery();
            while (rs.next()) {
                citem.addItem(rs.getString("Itemname"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }  public PageFormat getPageFormat(PrinterJob pj){
       PageFormat pf = pj.defaultPage();
       Paper paper = pf.getPaper();
       
       double bodyHeight = bHeight;
       double headerHeight = 5.0;
       double footerHeight = 5.0;
       double width = cm_to_pp(8);
       double height = cm_to_pp(headerHeight + bodyHeight + footerHeight);
       paper.setSize(width, height);
       paper.setImageableArea(0,10,width,height - cm_to_pp (1));
       
  pf.setOrientation(PageFormat.PORTRAIT);
  pf.setPaper(paper);
  
  return pf;
  }
  protected static double cm_to_pp(double cm){
  return toPP1 (cm * 0.393400787);
  } 
  protected static double toPP1(double inch){
  
  return inch *72d;
  }
  
  public class BillPrintable implements Printable{

  
        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
            
        
        
        int r = itemName.size();
       ImageIcon icon = new ImageIcon("C:\\Users\\AnthonyCee\\Documents\\NetBeansProjects\\QUICKSTOCKER\\src\\fastest.png") ; 
       int result = NO_SUCH_PAGE;
       if (pageIndex ==0){
       
       Graphics2D g2d = (Graphics2D) graphics;
       double width = pageFormat.getImageableWidth();
       g2d.translate((int) pageFormat.getImageableX(),(int) pageFormat.getImageableY());
       
       //fontmetrice metrice 2d.getformat
       try{
       
       int y = 20;
       int yshift = 10;
       int headerRectHeight = 15;
       
       g2d.setFont(new Font("Monospaced",Font.PLAIN,9));
       g2d.drawImage(icon.getImage(),50,20,90,30,rootPane);y  += yshift + 30;
       g2d.drawString(".......................................",12,y);y += yshift;
       g2d.drawString("Jeacosoft Software Company",12, y); y +=yshift;
       g2d.drawString(" Email:jeacsoft@gmail.com ", 12, y); y +=yshift;
       g2d.drawString(" Tel:+2348085189422/+2347034965611 ", 12, y); y +=yshift;
       g2d.drawString(" WhatsApp:+2347034965611 ", 12, y); y +=yshift;
       g2d.drawString("....................................", 12, y); y+=headerRectHeight;

       g2d.drawString("Item Name              Price", 10, y); y +=yshift;
       
       g2d.drawString("....................................", 10, y); y+=headerRectHeight;
       
       for(int s = 0; s<r; s++){
       
        g2d.drawString(" "+itemName.get(s)+"         ", 10, y); y+=yshift;
        g2d.drawString(" "+Quantity.get(s)+"*"+ itemPrice.get(s)      , 10, y); g2d.drawString("N"+subtotal.get(s),140,y); y+=yshift;
        
              }
       
  g2d.drawString("....................................", 10, y); y+=yshift;
 g2d.drawString(" Total Amout :          "+ "N" + lgt.getText()+"  ", 10, y); y+=yshift;
  g2d.drawString("....................................", 10, y); y+=yshift;
  g2d.drawString("Cash         :         "+" N" + txtcash.getText()+"  ", 10, y); y+=yshift;
  g2d.drawString("....................................", 10, y); y+=yshift;
  g2d.drawString("Balance      :          "+ txtbal.getText()+"   ", 10, y); y+=yshift;

      
  g2d.drawString("....................................", 10, y); y+=yshift;
 g2d.drawString(" Thanks for your patronage, see you soon", 10, y); y+=yshift;
  g2d.drawString("....................................", 10, y); y+=yshift;
  g2d.drawString("Powered by : Jeacosoft Technology", 10, y); y+=yshift;
  g2d.drawString("....................................", 10, y); y+=yshift;
  g2d.drawString("Your satisfaction is our gain", 10, y); y+=yshift;

  
       }catch(Exception e){
       e.printStackTrace();
       }
       result = PAGE_EXISTS;
       }


        return result;
        }
    }
   
    public void showme() {
        try {
            String date = ((JTextField) idate.getDateEditor().getUiComponent()).getText();
            String s = "SELECT * FROM `dailyanalysistable` WHERE Date = '" + date + "'";
            ps = con.prepareStatement(s);
            rs = ps.executeQuery();
            if (rs.next()) {

                ldsale.setText("N" + rs.getString("TotalDailySales"));

                ldexp.setText("N" + rs.getString("TotalExpenses"));

                ldbal.setText("N" + rs.getString("NetBalance"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    //this will show a copy of sales activity to the adm void{
    public void addmin() {
     index admin = new index();

        try {
            String date = ((JTextField) idate.getDateEditor().getUiComponent()).getText();
            String s = "SELECT * FROM `dailyanalysistable` WHERE Date = '" + date + "'";
            ps = con.prepareStatement(s);
            rs = ps.executeQuery();
            if (rs.next()) {

                admin.dailysale.setText("N" + rs.getString("TotalDailySales"));

                admin.texp.setText("N" + rs.getString("TotalExpenses"));

                admin.tbal.setText("N" + rs.getString("NetBalance"));

            }
        } catch (SQLException ex) {

        }

    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        Expensesbook exb = new Expensesbook();
        dplay.add(exb);
        exb.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Expensesbook expb = new Expensesbook();
        dplay.add(expb);
        expb.show();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        search sch =  new search();
        dplay.add(sch);
        sch.show();
                
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         frontpage fp = new frontpage();
        this.hide();
        fp.show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        frontpage fp = new frontpage();
        this.hide();
        fp.show();
        this.dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        showme();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtqty.setText("");
        txtsearch.setText("");
        ltotal.setText("");
        lgt.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        bHeight = Double.valueOf(itemName.size());
        //JOptionPane.showMessageDialog(rootPane,bHeight);

        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable(new BillPrintable(),getPageFormat(pj));

        try{
            pj.print();

        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableshowMouseClicked
        // show on mouse click on the jtext field

        int i = tableshow.getSelectedRow();
        TableModel model = tableshow.getModel();
        // txtid.setText(model.getValueAt(i,0).toString());
        citem.setSelectedItem(model.getValueAt(i, 1).toString());
        lprice.setText(model.getValueAt(i, 3).toString());

        try {
            String combo = (String) citem.getSelectedItem();
            String search1 = "SELECT SalesPrice,`Quantity` FROM `admintable` WHERE ItemName = ?";
            ps = con.prepareStatement(search1);
            ps.setString(1, combo);
            rs = ps.executeQuery();
            // citem.removeAllItems();
            while (rs.next()) {

                String add2 = rs.getString("Quantity");
                lstock.setText(add2);

            }

        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableshowMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            int conf = JOptionPane.showConfirmDialog(this, "Perform transaction?", "CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (txtqty.getText().equals("") || txtqty.getText().equals("0")) {

                JOptionPane.showMessageDialog(this, "Please enter quantity of product purchased");
            } else {
                if (conf == JOptionPane.YES_OPTION) {
                    String date = ((JTextField) idate.getDateEditor().getUiComponent()).getText();

                    // calculating the les and savings
                    String combo = (String) citem.getSelectedItem();
                    String check = "select `Quantity` from `admintable` where  `ItemName` = '" + combo + "'";

                    ps = con.prepareStatement(check);
                    //ps.setString (1, txtbal.getText());
                    rs = ps.executeQuery();
                    while (rs.next()) {
                        double saleqty = Double.parseDouble(txtqty.getText());
                        int stockqty;

                        stockqty = rs.getInt("Quantity");

                        if (stockqty < saleqty) {
                            JOptionPane.showMessageDialog(this, "You don't have enough or you have run out of  " + "" + "".concat("" + "" + citem.getSelectedItem()));

                        } else {

                            try {

                                try {
                                    double price = Double.parseDouble(lprice.getText());
                                    double qty = Double.parseDouble(txtqty.getText());

                                    double result = price * qty;
                                    ltotal.setText("" + result);

                                    //coding for  the accumalation grandtotal
                                    accum += result;
                                    lgt.setText("" + accum);

                                    String sql = "UPDATE `admintable` SET  `Quantity` = (`Quantity`- ?) WHERE ItemName = ?";
                                    ps = con.prepareStatement(sql);
                                    ps.setString(1, txtqty.getText());
                                    ps.setString(2, citem.getSelectedItem().toString());
                                    int sub = ps.executeUpdate();
                                    if (sub > 0) {
                                        //  JOptionPane.showMessageDialog(this, "good");
                                        fetchdata();
                                    }
                                } catch (SQLException ex) {
                                    // JOptionPane.showMessageDialog(this, "notgood");
                                    Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);

                                }

                                try {

                                    String sql1 = "UPDATE `detailtable` SET `QuantityOut`=(`QuantityOut` + ? ),`BalanceQuantity`=( `QuantityPurchased` - ?) WHERE ItemName = ?";
                                    ps = con.prepareStatement(sql1);
                                    ps.setString(1, txtqty.getText());
                                    ps.setString(2, txtqty.getText());
                                    ps.setString(3, citem.getSelectedItem().toString());
                                    int sub = ps.executeUpdate();
                                    if (sub > 0) {
                                        // JOptionPane.showMessageDialog(this, "good");
                                        fetchdata();
                                    }
                                } catch (SQLException ex) {
                                    // JOptionPane.showMessageDialog(this, "notgood");
                                    Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);

                                }

                                String ins = "INSERT INTO `dailyinventorytable`( `ItemName`, `Price`, `Quantity`, `TotalAmount`, `QuantityInStock`, `Date`) VALUES (?,?,?,?,?,?)";
                                ps = con.prepareStatement(ins);
                                ps.setString(1, citem.getSelectedItem().toString());
                                ps.setString(2, lprice.getText());
                                ps.setString(3, txtqty.getText());
                                ps.setString(4, ltotal.getText());
                                ps.setString(5, lstock.getText());
                                ps.setString(6, date);
                                int subm = ps.executeUpdate();
                                if (subm > 0) {
                                    //  JOptionPane.showMessageDialog(this, "ok");
                                }

                            } catch (SQLException ex) {
                                // JOptionPane.showMessageDialog(this, "not");
                                Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);

                            }

                            try {

                                String qry = "select * from  `dailyanalysistable` where Date = '" + date + "'";
                                ps = con.prepareStatement(qry);
                                rs = ps.executeQuery();

                                if (!rs.next()) {

                                    try {

                                        // Submiting the b/f,opening balance and the date
                                        String sql5 = "INSERT INTO `dailyanalysistable`( `TotalDailySales`, `TotalExpenses`, `NetBalance`, `Date`) VALUES (?,?,?,?)";
                                        ps = con.prepareStatement(sql5);
                                        ps.setString(1, ltotal.getText());
                                        ps.setDouble(2, 0);
                                        ps.setDouble(3, 0);
                                        ps.setString(4, date);

                                        int k1 = ps.executeUpdate();
                                        if (k1 > 0) {

                                            JOptionPane.showMessageDialog(this, "Transaction was Successful");
                                            showme();

                                        }

                                    } catch (SQLException ex) {

                                        JOptionPane.showMessageDialog(this, "Submission Failed");
                                        Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
                                    }

                                } else {
                                    try {

                                        String sql2 = "UPDATE `dailyanalysistable` SET `TotalDailySales`= (`TotalDailySales` + '" + ltotal.getText() + "') , `NetBalance`= (`TotalDailySales` - `TotalExpenses`) where Date = '" + date + "'";
                                        ps = con.prepareStatement(sql2);
                                        int q = ps.executeUpdate();

                                        if (q > 0) {
                                            JOptionPane.showMessageDialog(this, "Transaction was Successful");
                                            showme();
                                            
                                            //adding the items and their corresponding info to printer
                                            itemName.add(citem.getSelectedItem().toString());
                                            Quantity.add(txtqty.getText());
                                            itemPrice.add(lprice.getText());
                                            subtotal.add(ltotal.getText());
                                            //totalAmount = totalAmount + Double.valueOf(ltotal.getText());
                                            txtqty.setText("0");

                                            //JOptionPane.showMessageDialog(this,"Updated was Successful");
                                        }

                                    } catch (SQLException ex) {
                                        //JOptionPane.showMessageDialog(this,"Update failed");
                                        Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
                                    }

                                    //                                    try {
                                        //
                                        //                                        String sql32 = "UPDATE `dailyanalysistable` SET `NetBalance`= (`TotalDailySales` - `TotalExpenses`) where Date = '" + date + "'";
                                        //                                        ps = con.prepareStatement(sql32);
                                        //                                        int q = ps.executeUpdate();
                                        //
                                        //                                        if (q > 0) {
                                            //
                                            //                                            JOptionPane.showMessageDialog(this, "Transaction was Successful");
                                            //                                            showme();
                                            //                                            txtqty.setText("0");
                                            //
                                            //                                        }
                                        //
                                        //                                    } catch (SQLException ex) {
                                        //                                        // JOptionPane.showMessageDialog(this,"Update failed");
                                        //                                        Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
                                        //                                    }

                                }

                            } catch (SQLException ex) {
                                Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);

                            }

                        }
                    }
                }

            }
            //}

        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void citemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citemActionPerformed
        // seting the corresponding values of the item on the conbobox on the following

    }//GEN-LAST:event_citemActionPerformed

    private void citemPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_citemPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_citemPopupMenuWillBecomeVisible

    private void citemPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_citemPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            String combo = (String) citem.getSelectedItem();
            String search1 = "SELECT SalesPrice,Quantity FROM `admintable` WHERE ItemName = ?";
            ps = con.prepareStatement(search1);
            ps.setString(1, combo);
            rs = ps.executeQuery();
            // citem.removeAllItems();
            while (rs.next()) {

                String add1 = rs.getString("SalesPrice");
                lprice.setText(add1);

                String add2 = rs.getString("Quantity");
                lstock.setText(add2);

            }
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_citemPopupMenuWillBecomeInvisible

    private void citemAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_citemAncestorMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_citemAncestorMoved

    private void citemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_citemItemStateChanged

    }//GEN-LAST:event_citemItemStateChanged

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        try {
            // search and display the items on both combo box and table
            String search = "SELECT * FROM `admintable` WHERE ItemName like '" + txtsearch.getText() + "%'";
            ps = con.prepareStatement(search);
            rs = ps.executeQuery();
            citem.removeAllItems();

            while (rs.next()) {

                citem.addItem(rs.getString("ItemName"));
                lprice.setText("");

                lstock.setText("");

            }

        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            String q = "select id, ItemName, Description,SalesPrice from admintable WHERE ItemName like '" + txtsearch.getText() + "%'";
            ps = con.prepareStatement(q);
            rs = ps.executeQuery();

            tableshow.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {

            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtcashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcashKeyReleased
        // TODO add your handling code here:
      //calculating the balance for a customer
      
      double sum = Double.parseDouble(lgt.getText());
      double cash = Double.parseDouble(txtcash.getText());
      double bal = cash - sum;
      txtbal.setText("N" + bal);
    }//GEN-LAST:event_txtcashKeyReleased

    private void txtqtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtqtyFocusGained
        // TODO add your handling code here:
        txtqty.setText("");
    }//GEN-LAST:event_txtqtyFocusGained

    private void txtcashFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcashFocusGained
        // TODO add your handling code here:
        txtcash.setText("");
    }//GEN-LAST:event_txtcashFocusGained

    private void txtsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusGained
        // TODO add your handling code here:
        txtsearch.setText("");
    }//GEN-LAST:event_txtsearchFocusGained

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please contact our customer service center at \nTel : +2348085189422 \nE-mail : jeacosoft@gmail.com \nWhatsApp : +23407034965611","Assistance Center",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> citem;
    private javax.swing.JDesktopPane dplay;
    private com.toedter.calendar.JDateChooser idate;
    private javax.swing.JLabel iname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel ldbal;
    public static javax.swing.JLabel ldexp;
    public static javax.swing.JLabel ldsale;
    private javax.swing.JLabel lgt;
    public static javax.swing.JLabel lprice;
    public static javax.swing.JLabel lstock;
    private javax.swing.JLabel ltotal;
    public static javax.swing.JTable tableshow;
    private javax.swing.JLabel txtbal;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
